name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  riverpod: 3.0.0-dev.17
  riverpod_annotation: 3.0.0-dev.17
  riverpod_shared_preferences: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.9.3
  lints: any
  riverpod_generator: 3.0.0-dev.17

flutter:
  uses-material-design: true
