name: riverpod_shared_preferences
description: An adapter to connect shared_preferences with riverpod
version: 0.0.1
repository: https://github.com/lucavenir/riverpod_shared_preferences

environment:
  sdk: ^3.8.1

dependencies:
  clock: ^1.1.2
  collection: ^1.19.1
  meta: ^1.16.0
  riverpod: 3.0.0-dev.17
  shared_preferences: ^2.5.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
